name: build and publish container image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: build and push image
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
